### ISSUE TITLE
Error when start with Angular 2

### ISSUE THREAD

**Issue by KeitaElric** [johannesjo/angular2-promise-buttons#3]
I applied promise button to my project use @angular version 2.4.8
When start project with webpack, I get error message "core_1.InjectionToken is not a constructor"

**Comment by johannesjo** [comment]
Thanks for reporting! I'll have a look at it.

**Comment by johannesjo** [comment]
The problem is that the library is using `Render2` and `InjectionToken` over `Renderer` and `OpaqueToken`. Both are only introduced in angular 4. I'm working on a solution to integrate a compatibility layer. I'm glad for any suggestions how to do implement such a thing.

For now you would have to upgrade to Angular 4 to use this lib, but I'll keep you updated.

**Comment by johannesjo** [comment]
Ok I modified everything to also work with Angular2. Could you please check, if it works for you with v1.0.7?

**Comment by KeitaElric** [comment]
It worked
Tk sir 😄
